### ISSUE TITLE
Dashboard: Indicate Errors and Sensor Type

### ISSUE THREAD

**Issue by margau** [firefly-serenity/decentral-air-quality-monitoring-server#3]
It would be very helpful, if frames containing errors are not just dropped, but the dashboard would indicate that the backend has received data containing an error code.
In this context, maybe "Type of connection" (TTN/Direct MQTT) with "last contact" and sensor type could be displayed too.
All this information could be very helpful when setting up an new node.

**Comment by ffly90** [comment]
Not sure if debugging info should be displayed on the frontend. Would it not be more logical to respond via mqtt? Is the node capable of subcribing to a topic to receive messages?

**Comment by margau** [comment]
Theoretically the node would be capable - but from a user perspective, when I'm trying to get a node up and running, I want to know from the backend if it received anything, and what it received.

So, for UX reasons, I think the backend should expose this.

**Comment by ffly90** [comment]
I agree, but still I do Not Think that the grafana frontend is the right place for that. I could build a minimalistic debugging page for your convenience. But when bringing a node up I still think that having the feedback from the backend on the node itself would be more logical from an ux perspective.

> So, for UX reasons, I think the backend should expose this.

I did not want to question this!

**Comment by ffly90** [comment]
I built a debugging page for each sensor ID. The page is a staticly generated html page that can be accessed via particle.nodelove.eu/debug/\<sensorID\>.html

**Comment by ffly90** [comment]
fr rejected but workaround given
